//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Element
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Element()
    {
        this.ElementProcedure = new HashSet<ElementProcedure>();
        this.PhotosElement = new HashSet<PhotosElement>();
        this.Entretiens = new HashSet<Entretien>();
        this.Remarque = new HashSet<Remarque>();
        this.EntretiensPrecedant = new HashSet<EntretiensPrecedant>();
    }

    public int Id { get; set; }
    public string NomElement { get; set; }
    public string NumeroElement { get; set; }
    public string DescriptionElement { get; set; }

    public virtual TypeEmplacement TypeEmplacements { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ElementProcedure> ElementProcedure { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PhotosElement> PhotosElement { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Entretien> Entretiens { get; set; }
    public virtual TypesElement TypesElement { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Remarque> Remarque { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EntretiensPrecedant> EntretiensPrecedant { get; set; }
}

public partial class ElementProcedure
{
    public int Id { get; set; }

    public virtual Element Elements { get; set; }
    public virtual Procedure Procedure { get; set; }
}

public partial class Entretien
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Entretien()
    {
        this.EntretiensProduits = new HashSet<EntretiensProduit>();
        this.EntretiensPrecedants = new HashSet<EntretiensPrecedant>();
        this.Remarque = new HashSet<Remarque>();
    }

    public int Id { get; set; }
    public string TitreEntretien { get; set; }
    public int Recurrence { get; set; }
    public string DescriptionEntretien { get; set; }
    public System.DateTime DateProchainEntretien { get; set; }

    public virtual Element Element { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EntretiensProduit> EntretiensProduits { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EntretiensPrecedant> EntretiensPrecedants { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Remarque> Remarque { get; set; }
}

public partial class EntretiensPrecedant
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EntretiensPrecedant()
    {
        this.Remarques = new HashSet<Remarque>();
    }

    public int Id { get; set; }
    public string NomEmploye { get; set; }
    public string PrenomEmploye { get; set; }
    public System.DateTime DateEntretienPrecedant { get; set; }
    public string DescriptionEntretienPrecedant { get; set; }

    public virtual Entretien Entretien { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Remarque> Remarques { get; set; }
    public virtual Element Elements { get; set; }
}

public partial class EntretiensProduit
{
    public int Id { get; set; }
    public double QuantiteProduitEntretien { get; set; }

    public virtual Entretien Entretien { get; set; }
    public virtual Produit Produit { get; set; }
}

public partial class Message
{
    public int Id { get; set; }
    public string Commentaires { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
}

public partial class PhotosElement
{
    public int Id { get; set; }
    public string SourcePhotoElement { get; set; }

    public virtual Element Elements { get; set; }
}

public partial class PhotosProduit
{
    public int Id { get; set; }
    public string SourcePhotoProduit { get; set; }

    public virtual Produit Produit { get; set; }
}

public partial class PhotosRemarque
{
    public int Id { get; set; }
    public string SourcePhotoRemarque { get; set; }

    public virtual Remarque Remarque { get; set; }
}

public partial class Procedure
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Procedure()
    {
        this.ElementProcedures = new HashSet<ElementProcedure>();
    }

    public int Id { get; set; }
    public string SourceProcedure { get; set; }
    public string NomProcedure { get; set; }
    public string DescriptionProcedure { get; set; }

    public virtual TypeEmplacement TypeEmplacement { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ElementProcedure> ElementProcedures { get; set; }
    public virtual TypesElement TypesMachines { get; set; }
}

public partial class Produit
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Produit()
    {
        this.EntretiensProduits = new HashSet<EntretiensProduit>();
        this.PhotosProduits = new HashSet<PhotosProduit>();
    }

    public int Id { get; set; }
    public string NomProduit { get; set; }
    public string DescriptionProduit { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EntretiensProduit> EntretiensProduits { get; set; }
    public virtual TypesProduit TypesProduit { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PhotosProduit> PhotosProduits { get; set; }
}

public partial class Remarque
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Remarque()
    {
        this.PhotosRemarques = new HashSet<PhotosRemarque>();
    }

    public int Id { get; set; }
    public string TitreRemarque { get; set; }
    public string DescriptionRemarque { get; set; }

    public virtual EntretiensPrecedant EntretiensPrecedant { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PhotosRemarque> PhotosRemarques { get; set; }
    public virtual Entretien Entretiens { get; set; }
    public virtual Element Elements { get; set; }
}

public partial class TypeEmplacement
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TypeEmplacement()
    {
        this.Procedure = new HashSet<Procedure>();
        this.Element = new HashSet<Element>();
    }

    public int Id { get; set; }
    public string NomTypeEmplacement { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Procedure> Procedure { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Element> Element { get; set; }
}

public partial class TypesElement
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TypesElement()
    {
        this.Procedure = new HashSet<Procedure>();
        this.Elements = new HashSet<Element>();
    }

    public int Id { get; set; }
    public string NomTypeElement { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Procedure> Procedure { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Element> Elements { get; set; }
}

public partial class TypesProduit
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TypesProduit()
    {
        this.Produits = new HashSet<Produit>();
    }

    public int Id { get; set; }
    public string NomTypeProduit { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Produit> Produits { get; set; }
}

public partial class Usager
{
    public int Id { get; set; }
    public string Nom { get; set; }
    public string Prenom { get; set; }
    public System.DateTime DateInscription { get; set; }
    public string MotDePasse { get; set; }
    public bool Administrateur { get; set; }
    public Nullable<System.Guid> UserGuid { get; set; }
    public string Hash { get; set; }
}
