//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class MainPltModelContainer : DbContext
{
    public MainPltModelContainer()
        : base("name=MainPltModelContainer")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Usager> Usagers { get; set; }
    public virtual DbSet<Element> Elements { get; set; }
    public virtual DbSet<Entretien> Entretiens { get; set; }
    public virtual DbSet<EntretiensProduit> EntretiensProduits { get; set; }
    public virtual DbSet<Produit> Produits { get; set; }
    public virtual DbSet<PhotosElement> PhotosElements { get; set; }
    public virtual DbSet<TypesElement> TypesElements { get; set; }
    public virtual DbSet<Procedure> Procedures { get; set; }
    public virtual DbSet<EntretiensPrecedant> EntretiensPrecedants { get; set; }
    public virtual DbSet<PhotosProduit> PhotosProduits { get; set; }
    public virtual DbSet<Remarque> Remarques { get; set; }
    public virtual DbSet<TypesProduit> TypesProduits { get; set; }
    public virtual DbSet<PhotosRemarque> PhotosRemarques { get; set; }
    public virtual DbSet<ElementProcedure> ElementProcedures { get; set; }
    public virtual DbSet<TypeEmplacement> TypeEmplacementSet { get; set; }
    public virtual DbSet<Message> Messages { get; set; }
}
